import {
  buildApplicationMatches,
  buildSwissEngineInput,
  swissPairingCriteriaSnapshot,
} from './application-adapter.mjs';
import {
  createBrowserWorkerFactory,
  SwissWorkerExecutor,
} from './worker-executor.mjs';
import {
  applicationPairingSignature,
  engineSignatureFromMatches,
  runInitialSwissPairing,
  runNextSwissPairingVariant,
  swissInputFingerprint,
} from './application-runner.mjs';
import {
  analyzeApplicationSwissRound,
  swissOperationFeedback,
} from './pairing-analysis.mjs';
import {
  createHybridSwissSnapshot,
  HYBRID_SWISS_SNAPSHOT_VERSION,
  isValidHybridSwissSnapshot,
  restoreHybridSwissStandings,
} from './hybrid-snapshot.mjs';
import {
  assertExplicitMatchOutcome,
  consumesSwissBye,
  hasRealOpponent,
  isResolvedMatch,
  MATCH_OUTCOME_KINDS,
  MATCH_OUTCOME_VERSION,
  readMatchOutcome,
  clearMatchRecordedData,
  writeMatchOutcome,
} from '../results/match-outcome.mjs';
import {
  calculatePlayedRoundAverages,
  calculateSwissStandings,
  createRoundScoringMeta,
  finalizeRoundNeutralScores,
  ROUND_SCORING_VERSION,
} from '../results/swiss-scoring.mjs';
import {
  ADMINISTRATIVE_FLOW_VERSION,
  ADMINISTRATIVE_REASONS,
  findOpenRoundMatch,
  matchContainsPlayer,
  resolveAdministrativeMatch,
  roundHasEnteredResults,
  analyzeRoundParticipantIntegrity,
  analyzeManualRoundBlocks,
} from '../results/administrative-flow.mjs';
import { describePlayerOutcome } from '../results/result-presentation.mjs';
import {
  BRACKET_PLACEMENTS_VERSION,
  inspectPersistedState,
  STATE_SCHEMA_VERSION,
} from '../results/persistence-compatibility.mjs';
import {
  PAIRING_DRAFT_VERSION,
  PairingDraftError,
  applyPairingExchange,
  applyTableNumberExchange,
  createPairingDraft,
  getPairingDraftPosition,
  listPairingDraftPositions,
  matchHasRecordedData,
  pairingDraftMatches,
  previewPairingExchange,
  resetPairingDraft,
  summarizePairingDraft,
  undoPairingExchange,
} from '../pairings/pairing-draft.mjs';
import {
  classifyPairingCandidate,
  sortPairingCandidates,
} from '../pairings/pairing-candidate.mjs';

export {
  analyzeApplicationSwissRound,
  applicationPairingSignature,
  buildApplicationMatches,
  buildSwissEngineInput,
  swissPairingCriteriaSnapshot,
  createBrowserWorkerFactory,
  engineSignatureFromMatches,
  runInitialSwissPairing,
  runNextSwissPairingVariant,
  swissInputFingerprint,
  swissOperationFeedback,
  SwissWorkerExecutor,
  createHybridSwissSnapshot,
  HYBRID_SWISS_SNAPSHOT_VERSION,
  isValidHybridSwissSnapshot,
  restoreHybridSwissStandings,
  assertExplicitMatchOutcome,
  consumesSwissBye,
  hasRealOpponent,
  isResolvedMatch,
  MATCH_OUTCOME_KINDS,
  MATCH_OUTCOME_VERSION,
  readMatchOutcome,
  clearMatchRecordedData,
  writeMatchOutcome,
  calculatePlayedRoundAverages,
  calculateSwissStandings,
  createRoundScoringMeta,
  finalizeRoundNeutralScores,
  ROUND_SCORING_VERSION,
  ADMINISTRATIVE_FLOW_VERSION,
  ADMINISTRATIVE_REASONS,
  findOpenRoundMatch,
  matchContainsPlayer,
  resolveAdministrativeMatch,
  roundHasEnteredResults,
  analyzeRoundParticipantIntegrity,
  analyzeManualRoundBlocks,
  describePlayerOutcome,
  BRACKET_PLACEMENTS_VERSION,
  inspectPersistedState,
  STATE_SCHEMA_VERSION,
  PAIRING_DRAFT_VERSION,
  PairingDraftError,
  applyPairingExchange,
  applyTableNumberExchange,
  createPairingDraft,
  getPairingDraftPosition,
  listPairingDraftPositions,
  matchHasRecordedData,
  pairingDraftMatches,
  previewPairingExchange,
  resetPairingDraft,
  summarizePairingDraft,
  undoPairingExchange,
  classifyPairingCandidate,
  sortPairingCandidates,
};
